PROBLEM_LIST = ['ex222','exc137','ex132a','ex132','ex152a','ex152b','ex152','ex144','ex212','ex242','ex252a','ex252']

PROBLEM_FEATURES = ['ntellsSinceElicit', 'ntellsSinceElicitKC', 'nElicitSinceTell', 'nElicitSinceTellKC', 'pctElicit',
			   'pctElicitKC', 'pctElicitSession', 'pctElicitKCSession', 'nTellSession', 'nTellKCSession', 'kcOrdering',
			   'kcOrderingSession', 'durationKCBetweenDecision', 'timeInSession', 'timeBetweenSession',
			   'timeOnTutoring',
			   'timeOnTutoringWE', 'timeOnTutoringPS', 'timeOnTutoringKC', 'timeOnTutoringKCWE', 'timeOnTutoringKCPS',
			   'avgTimeOnStep', 'avgTimeOnStepWE', 'avgTimeOnStepPS', 'avgTimeOnStepKC', 'avgTimeOnStepKCWE',
			   'avgTimeOnStepKCPS', 'timeOnLastStepKCPS', 'timeOnTutoringSession', 'timeOnTutoringSessionWE',
			   'timeOnTutoringSessionPS', 'avgTimeOnStepSession', 'avgTimeOnStepSessionWE', 'avgTimeOnStepSessionPS',
			   'nTotalHint', 'nTotalHintSession', 'nHintKC', 'nHintSessionKC', 'AvgTimeOnStepWithHint',
			   'durationSinceLastHint', 'stepsSinceLastHint', 'stepsSinceLastHintKC', 'totalTimeStepsHint',
			   'totalStepsHint',
			   'earlyTraining', 'simpleProblem', 'nKCs', 'nKCsAsPS', 'nKCsSession', 'nKCsSessionPS',
			   'newLevelDifficulty',
			   'nPrincipleInProblem', 'quantitativeDegree', 'nTutorConceptsSession', 'tutAverageConcepts',
			   'tutAverageConceptsSession', 'tutConceptsToWords', 'tutConceptsToWordsSession', 'tutAverageWords',
			   'tutAverageWordsSession', 'tutAverageWordsPS', 'tutAverageWordsSessionPS', 'nDistinctPrincipleInSession',
			   'nPrincipleInSession', 'problemDifficuly', 'problemCompexity', 'problemCategory', 'pctCorrect',
			   'pctOverallCorrect', 'nCorrectKC', 'nIncorrectKC', 'pctCorrectKC', 'pctOverallCorrectKC',
			   'nCorrectKCSession',
			   'nIncorrectKCSession', 'pctCorrectSession', 'pctCorrectKCSession', 'pctOverallCorrectSession',
			   'pctOverallCorrectKCSession', 'nStepSinceLastWrong', 'nStepSinceLastWrongKC', 'nWEStepSinceLastWrong',
			   'nWEStepSinceLastWrongKC', 'nStepSinceLastWrongSession', 'nStepSinceLastWrongKCSession',
			   'nWEStepSinceLastWrongSession', 'nWEStepSinceLastWrongKCSession', 'timeSinceLastWrongStepKC',
			   'nCorrectPSStepSinceLastWrong', 'nCorrectPSStepSinceLastWrongKC',
			   'nCorrectPSStepSinceLastWrongKCSession',
			   'pctCorrectPrin', 'pctCorrectPrinSession', 'nStepSinceLastWrongPrin', 'nWEStepSinceLastWrongPrin',
			   'nStepSinceLastWrongPrinSession', 'nWEStepSinceLastWrongPrinSession', 'nCorrectPSStepSinceLastWrongPrin',
			   'nCorrectPSStepSinceLastWrongPrinSession', 'pctCorrectFirst', 'nStepsSinceLastWrongFirst',
			   'nWEStepSinceLastWrongFirst', 'nCorrectPSStepSinceLastWrongFirst', 'pctCorrectLastProb',
			   'pctCorrectLastProbPrin', 'pctCorrectAdd2Select', 'pctCorrectAdd3Select', 'pctCorrectCompSelect',
			   'pctCorrectDeMorSelect', 'pctCorrectIndeSelect', 'pctCorrectMutualSelect', 'pctCorrectAdd2Apply',
			   'pctCorrectAdd3Apply', 'pctCorrectCompApply', 'pctCorrectDeMorApply', 'pctCorrectIndeApply',
			   'pctCorrectMutualApply', 'pctCorrectAdd2All', 'pctCorrectAdd3All', 'pctCorrectCompAll',
			   'pctCorrectDeMorAll',
			   'pctCorrectIndeAll', 'pctCorrectMutualAll', 'pctCorrectSelectMain', 'nAdd2Prob', 'nAdd3Prob',
			   'nDeMorProb',
			   'nIndeProb', 'nCompProb', 'nMutualProb']

STEP_FEATURES = ['ntellsSinceElicit', 'ntellsSinceElicitKC', 'nElicitSinceTell', 'nElicitSinceTellKC', 'pctElicit', 'pctElicitKC',
	 'pctElicitSession', 'pctElicitKCSession', 'nTellSession', 'nTellKCSession', 'kcOrdering', 'kcOrderingSession',
	 'kcOrderingPb', 'durationKCBetweenDecision', 'timeInSession', 'timeBetweenSession', 'timeOnCurrentProblem',
	 'timeOnTutoring', 'timeOnTutoringWE', 'timeOnTutoringPS', 'timeOnTutoringKC', 'timeOnTutoringKCWE',
	 'timeOnTutoringKCPS', 'avgTimeOnStep', 'avgTimeOnStepWE', 'avgTimeOnStepPS', 'avgTimeOnStepKC',
	 'avgTimeOnStepKCWE', 'avgTimeOnStepKCPS', 'timeOnLastStepKCPS', 'timeOnTutoringSession', 'timeOnTutoringSessionWE',
	 'timeOnTutoringSessionPS', 'avgTimeOnStepSession', 'avgTimeOnStepSessionWE', 'avgTimeOnStepSessionPS',
	 'timeOnTutoringProblem', 'timeOnTutoringProblemWE', 'timeOnTutoringProblemPS', 'avgTimeOnStepProblem',
	 'avgTimeOnStepProblemWE', 'avgTimeOnStepProblemPS', 'nTotalHint', 'nTotalHintSession', 'nHintKC', 'nHintSessionKC',
	 'nTotalHintProblem', 'AvgTimeOnStepWithHint', 'durationSinceLastHint', 'stepsSinceLastHint',
	 'stepsSinceLastHintKC', 'totalTimeStepsHint', 'totalStepsHint', 'earlyTraining', 'simpleProblem', 'nKCs',
	 'nKCsAsPS', 'nKCsSession', 'nKCsSessionPS', 'newLevelDifficulty', 'performanceDifficulty', 'nPrincipleInProblem',
	 'quantitativeDegree', 'nTutorConceptsSession', 'tutAverageConcepts', 'tutAverageConceptsSession',
	 'tutConceptsToWords', 'tutConceptsToWordsSession', 'tutAverageWords', 'tutAverageWordsSession',
	 'tutAverageWordsPS', 'tutAverageWordsSessionPS', 'nDistinctPrincipleInSession', 'nPrincipleInSession',
	 'principleDifficulty', 'principleCategory', 'problemDifficuly', 'problemCompexity', 'problemCategory',
	 'pctCorrect', 'pctOverallCorrect', 'nCorrectKC', 'nIncorrectKC', 'pctCorrectKC', 'pctOverallCorrectKC',
	 'nCorrectKCSession', 'nIncorrectKCSession', 'pctCorrectSession', 'pctCorrectKCSession', 'pctOverallCorrectSession',
	 'pctOverallCorrectKCSession', 'nStepSinceLastWrong', 'nStepSinceLastWrongKC', 'nWEStepSinceLastWrong',
	 'nWEStepSinceLastWrongKC', 'nStepSinceLastWrongSession', 'nStepSinceLastWrongKCSession',
	 'nWEStepSinceLastWrongSession', 'nWEStepSinceLastWrongKCSession', 'timeSinceLastWrongStepKC',
	 'nCorrectPSStepSinceLastWrong', 'nCorrectPSStepSinceLastWrongKC', 'nCorrectPSStepSinceLastWrongKCSession',
	 'pctCorrectPrin', 'pctCorrectPrinSession', 'nStepSinceLastWrongPrin', 'nWEStepSinceLastWrongPrin',
	 'nStepSinceLastWrongPrinSession', 'nWEStepSinceLastWrongPrinSession', 'nCorrectPSStepSinceLastWrongPrin',
	 'nCorrectPSStepSinceLastWrongPrinSession', 'pctCorrectFirst', 'nStepsSinceLastWrongFirst',
	 'nWEStepSinceLastWrongFirst', 'nCorrectPSStepSinceLastWrongFirst', 'pctCorrectLastProb', 'pctCorrectLastProbPrin',
	 'pctCorrectAdd2Select', 'pctCorrectAdd3Select', 'pctCorrectCompSelect', 'pctCorrectDeMorSelect',
	 'pctCorrectIndeSelect', 'pctCorrectMutualSelect', 'pctCorrectAdd2Apply', 'pctCorrectAdd3Apply',
	 'pctCorrectCompApply', 'pctCorrectDeMorApply', 'pctCorrectIndeApply', 'pctCorrectMutualApply', 'pctCorrectAdd2All',
	 'pctCorrectAdd3All', 'pctCorrectCompAll', 'pctCorrectDeMorAll', 'pctCorrectIndeAll', 'pctCorrectMutualAll',
	 'pctCorrectSelectMain', 'nAdd2Prob', 'nAdd3Prob', 'nDeMorProb', 'nIndeProb', 'nCompProb', 'nMutualProb']


MEDIAN_THRESHOLD_LTR = {
	'problem': 0.8970852298974328,
    'exc137': 0.40311465770021915,
    'ex132a': 0.5250410230715032,
    'ex132': 0.2667084886367972,
    'ex152a': 0.844492639703784,
    'ex152b': 0.698272415267164,
    'ex152': 1.1361785010421235,
    'ex212':  1.9690589181821827,
    'ex242': 1.6843242878456675,
    'ex252a': 2.9618163979860253,
    'ex252': 0.812536817452882
}

MEDIAN_THRESHOLD_STR_POSITIVE = {
	'problem': 0.0659,
    'exc137': 0.0013,
    'ex132a': 0.00132,
    'ex132': 0.00156,
    'ex152a': 0.00173,
    'ex152b': 0.00143,
    'ex152': 0.00133,
    'ex212': 0.00348,
    'ex242': 0.00295,
    'ex252a': 0.00675,
    'ex252': 0.00175
}

MEDIAN_THRESHOLD_STR_NEGATIVE = {
	'problem': -0.0856,
    'exc137': -0.0008,
    'ex132a': -0.00113,
    'ex132': -0.00155,
    'ex152a': -0.00188,
    'ex152b': -0.00163,
    'ex152': -0.0015,
    'ex212': -0.00435,
    'ex242': -0.0036,
    'ex252a': -0.009,
    'ex252': -0.00237
}

MAX_LENGTH = {
	'problem': 12,
    'exc137': 39,
    'ex132a': 71,
    'ex132': 205,
    'ex152a': 106,
    'ex152b': 89,
    'ex152': 142,
    'ex212':  52,
    'ex242': 81,
    'ex252a': 34,
    'ex252': 111
}